# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7abcc981bf5ee2ef82ece4f6a373175859bf77b216a1093a6b5f4f231c95d2d5e5087a0b5142629166f8ce328af840d76d5448ede4095aaa9693bd591f20fd05

test:
  secret_key_base: 1f028dd0bcb4bf3bd475a8f535971a974e78610f2d7c57059633c737e4b90e23e031a69d673bcf24bc7d8575486a7c72e026531163b1db338b5172c4bfd98b7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
